version: '3.8'

services:
  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.3
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.3
    environment:
      - LS_JAVA_OPTS="-Xmx256m -Xms256m"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elk
    ports:
      - "5044:5044"
    restart: always

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=changeme
    networks:
      - elk
    ports:
      - "5601:5601"
    restart: always

volumes:
  esdata:
    driver: local

networks:
  elk:
    driver: bridge
